### PR TITLE
Support Kotlin 1.9.10

### LINKED ISSUE #379: Support Kotlin 1.8.21
Hello 👋 

Awesome work on the library! By any chance there will be a new version released soon that supports Kotlin v1.8.21? 

I tried updating it ([link](https://github.com/dariuszkuc/kotlin-compile-testing/commit/c6f8742aa4c8a3c79b6b5f32eaf0a1185efdb855)) but sadly there is some change in behavior in v1.8.20 that breaks JS compiler. Nothing jumps out from the [release notes](https://kotlinlang.org/docs/whatsnew1820.html) - they did add alpha support for new JS IR compiler but that "shouldn't" affect the legacy compiler.

After updating to v1.8.20+ JS compilation fails asking to set some IR properties (`-ir-output-dir` and `-ir-output-name`). I tried updating the default [`KotlinJsCompilation#jsArgs()`](https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/core/src/main/kotlin/com/tschuchort/compiletesting/KotlinJsCompilation.kt#L75-L95) args to include those but that didn't work either, i.e. I added the following

```kotlin
args.moduleName = "KCT"
args.outputDir = outputDir.toString()
```

With the above JS compilation runs but does not produce any outputs.... Any help would be appreciated!

### LINKED ISSUE #390: Support Kotlin 1.9.20
1.9.20-Beta appears to remove the `setUseIR` function, so tests crash at runtime.
```
'void org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setUseIR(boolean)'
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setUseIR(boolean)'
	at com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:304)
	at com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:279)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.commonArguments(AbstractKotlinCompilation.kt:172)
	at com.tschuchort.compiletesting.KotlinCompilation.commonK2JVMArgs(KotlinCompilation.kt:279)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:452)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:628)
	at dev.drewhamilton.poko.PokoCompilerPluginTest.compilation of valid class succeeds(PokoCompilerPluginTest.kt:221)
```

### PR DESCRIPTION
**Pull request by 3flex**
Note - I have no plans to update this for Kotlin 1.9.20, see https://github.com/tschuchortdev/kotlin-compile-testing/pull/394#issuecomment-1788188847.

---

@BoD I hope you don't mind but I've forked your PR #388 as I've also spent time trying to upgrade to a more recent Kotlin version and looking into the failures. The missing piece is the last commit https://github.com/tschuchortdev/kotlin-compile-testing/pull/394/commits/796903816e7034759c87376b1e52acf3fa697d0a. I also rebased on #380 as that's where some of the initial changes came from.

* Closes #362 
* Closes #368 
* Closes #380 
* Closes #388 
* Closes #383 
* Closes #379 
* Closes #390

### CODE REVIEW

**Comment by BoD** [comment]
> I hope you don't mind but I've forked your PR

Not at all. This is great! And hope this can be merged/released 👍

**Comment by 3flex** [comment]
1.9.20 is in process of being released, and I spent more time updating this PR to be compatible, but ran into a couple of issues.

I found this fork, which I plan to switch to, as it's already updated to Kotlin 1.9.20: https://github.com/ZacSweers/kotlin-compile-testing. The declared goal of the fork is to keep up to date with new Kotlin releases and Zac as some will know is a very active developer who already maintains a number of smaller Kotlin-related projects, so I have faith that the fork will continue to be maintained.

I'll leave this open in case it's merged but I have no plans to update it for 1.9.20.
